const github = require('@actions/github');
const core = require('@actions/core');

class GitHubClient {
  constructor(token) {
    this.octokit = github.getOctokit(token);
    this.context = github.context;
  }

  /**
   * Get PR metadata (title, description, files changed)
   * @returns {Promise<Object>} PR metadata
   */
  async getPRMetadata() {
    try {
      const { data: pr } = await this.octokit.rest.pulls.get({
        owner: this.context.repo.owner,
        repo: this.context.repo.repo,
        pull_number: this.context.payload.pull_request.number,
      });

      return {
        number: pr.number,
        title: pr.title,
        description: pr.body || '',
        filesChanged: pr.changed_files,
        additions: pr.additions,
        deletions: pr.deletions,
        head: pr.head.sha,
        base: pr.base.sha,
      };
    } catch (error) {
      core.error(`Failed to get PR metadata: ${error.message}`);
      throw error;
    }
  }

  /**
   * Get the PR diff
   * @returns {Promise<string>} The PR diff
   */
  async getPRDiff() {
    try {
      const { data: files } = await this.octokit.rest.pulls.listFiles({
        owner: this.context.repo.owner,
        repo: this.context.repo.repo,
        pull_number: this.context.payload.pull_request.number,
      });

      // Construct a readable diff from the files
      let diff = '';
      for (const file of files) {
        diff += `\n## File: ${file.filename}\n`;
        diff += `Status: ${file.status}\n`;
        diff += `Changes: +${file.additions} -${file.deletions}\n\n`;

        if (file.patch) {
          diff += '```diff\n';
          diff += file.patch;
          diff += '\n```\n\n';
        }
      }

      core.info(`Retrieved diff for ${files.length} files`);
      return diff;
    } catch (error) {
      core.error(`Failed to get PR diff: ${error.message}`);
      throw error;
    }
  }

  /**
   * Get a file from the PR branch
   * @param {string} filePath - Path to the file
   * @returns {Promise<string|null>} File content or null if not found
   */
  async getFileFromPR(filePath) {
    try {
      const { data } = await this.octokit.rest.repos.getContent({
        owner: this.context.repo.owner,
        repo: this.context.repo.repo,
        path: filePath,
        ref: this.context.payload.pull_request.head.sha,
      });

      if (data.content) {
        // Content is base64 encoded
        const content = Buffer.from(data.content, 'base64').toString('utf-8');
        core.info(`Successfully read ${filePath} from PR branch`);
        return content;
      }

      return null;
    } catch (error) {
      if (error.status === 404) {
        core.warning(`File ${filePath} not found in PR branch`);
        return null;
      }
      core.error(`Failed to read ${filePath}: ${error.message}`);
      throw error;
    }
  }

  /**
   * Post a review comment on the PR
   * @param {string} reviewBody - The review comment body
   * @param {Object} metrics - Review metrics (blocking, high, medium counts)
   * @returns {Promise<void>}
   */
  async postReviewComment(reviewBody, metrics) {
    try {
      const formattedBody = this.formatReviewComment(reviewBody, metrics);

      await this.octokit.rest.issues.createComment({
        owner: this.context.repo.owner,
        repo: this.context.repo.repo,
        issue_number: this.context.payload.pull_request.number,
        body: formattedBody,
      });

      core.info('Successfully posted review comment on PR');
    } catch (error) {
      core.error(`Failed to post review comment: ${error.message}`);
      throw error;
    }
  }

  /**
   * Format the review comment with header and footer
   * @private
   */
  formatReviewComment(reviewBody, metrics) {
    const header = `# AI Code Review\n\n`;
    const summary = this.generateSummary(metrics);
    const footer = `\n\n---\n\n*This review was generated by the [Ruhil AI Code Reviewer](https://github.com/vikashruhil/ai-agent-manager) using Claude AI with project-specific patterns from CLAUDE.md*`;

    return header + summary + '\n\n' + reviewBody + footer;
  }

  /**
   * Generate a summary section based on metrics
   * @private
   */
  generateSummary(metrics) {
    const { blockingCount, highCount, mediumCount, totalIssues } = metrics;

    if (totalIssues === 0) {
      return '✅ **No issues found!** This PR looks good to merge.';
    }

    let summary = '## Summary\n\n';

    if (blockingCount > 0) {
      summary += `🔴 **${blockingCount} BLOCKING issue${blockingCount > 1 ? 's' : ''}** - Must fix before merge\n`;
    }
    if (highCount > 0) {
      summary += `🟡 **${highCount} HIGH priority issue${highCount > 1 ? 's' : ''}** - Should fix before merge\n`;
    }
    if (mediumCount > 0) {
      summary += `🟢 **${mediumCount} MEDIUM priority issue${mediumCount > 1 ? 's' : ''}** - Consider fixing\n`;
    }

    return summary;
  }
}

module.exports = GitHubClient;
